<a href="https://colab.research.google.com/github/lauratpaes/Anna-Clara-_-Laura_-Lavinia/blob/main/tarefa03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
df = pd.read_excel('dados_semana03.xlsx')
df
df = pd.DataFrame({
    "animal": [
        'plebeia sp.', 'plebeia sp.', 'formigas', 'abelha-jataí',
        'trigona spinipes', 'danaus plexippus', 'formigas',
        'abelha-jataí', 'beija-flor-tesoura', 'danaus plexippus',
        'formigas', 'danaus plexippus', 'eupetomena macroura',
        'hermeuptychia hermes', 'abelha-jataí', 'tribo augochlorini',
        'apis mellifera', 'abelha-jataí', 'trigona spinipes', 'abelha-jataí'
    ],  # nominal
    "número_visitas": [
       1, 2, 2, 15, 1, 1, 4, 3, 1, 2, 4, 1, 2, 3, 15, 4, 2, 17, 11, 21
    ],  # discreta
})
df.head()

             animal  número_visitas
0       plebeia sp.               1
1       plebeia sp.               2
2          formigas               2
3      abelha-jataí              15
4  trigona spinipes               1

#Tabelas de frequências

In [8]:
# Frequência simples da variável nominal animal
freq_animal = df['animal'].value_counts()
freq_animal

animal
abelha-jataí            5
formigas                3
danaus plexippus        3
plebeia sp.             2
trigona spinipes        2
beija-flor-tesoura      1
eupetomena macroura     1
hermeuptychia hermes    1
tribo augochlorini      1
apis mellifera          1
Name: count, dtype: int64

In [17]:
# Frequência simples da variável discreta número de visitas
freq_número_visitas = df['número_visitas'].value_counts()
freq_número_visitas

número_visitas
1     5
2     5
4     3
15    2
3     2
17    1
11    1
21    1
Name: count, dtype: int64

In [19]:
# frequência relativa da variável nominal animal
freq_animal_rel = df['animal'].value_counts(normalize=True) * 100
freq_animal_rel

animal
abelha-jataí            25.0
formigas                15.0
danaus plexippus        15.0
plebeia sp.             10.0
trigona spinipes        10.0
beija-flor-tesoura       5.0
eupetomena macroura      5.0
hermeuptychia hermes     5.0
tribo augochlorini       5.0
apis mellifera           5.0
Name: proportion, dtype: float64

In [20]:
# Frequência da variável discreta número de visitas
freq_número_visitas_rel = df['número_visitas'].value_counts(normalize=True) * 100
freq_número_visitas_rel
#

número_visitas
1     25.0
2     25.0
4     15.0
15    10.0
3     10.0
17     5.0
11     5.0
21     5.0
Name: proportion, dtype: float64

# Gráficos

##Gráfico de barras

In [ ]:
plt.figure(figsize=(6, 4))
sns.countplot(data=dados, x="Animal", color='pink')
plt.title("Número de parcelas por ambiente")
plt.xlabel("Acia")
plt.show()